<a href="https://www.kaggle.com/code/nilotpalmaitra/introduction-to-pandas?scriptVersionId=199092430" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

**Basic Introduction to Pandas for understanding** please upvote if you like it :))

In [ ]:
import datetime
print(f"Last updated: {datetime.datetime.now()}")

In [ ]:
import pandas as pd

# Print the version
print(f"pandas version: {pd.__version__}")

## 1. Datatypes

pandas has two main datatypes, `Series` and `DataFrame`.
* [`pandas.Series`](https://pandas.pydata.org/docs/reference/api/pandas.Series.html) - a 1-dimensional column of data.
* [`pandas.DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) (most common) - a 2-dimesional table of data with rows and columns.

You can create a `Series` using `pd.Series()` and passing it a Python list.

In [ ]:
# Creating a series of car types
cars = pd.Series(["BMW", "Toyota", "Honda"])
cars

In [ ]:
# Creating a series of colours
colours = pd.Series(["Blue", "Red", "White"])
colours

In [ ]:
# Creating a DataFrame of cars and colours
car_data = pd.DataFrame({"Car type": cars, 
                         "Colour": colours})
car_data

In [ ]:
# Example solution

# Make a Series of different foods
foods = pd.Series(["Almond butter", "Eggs", "Avocado"])

# Make a Series of different dollar values 
prices = pd.Series([9, 6, 2])

# Combine your Series of foods and dollar values into a DataFrame
food_data = pd.DataFrame({"Foods": foods,
                          "Price": prices})

food_data

In [ ]:
# Import car sales data
car_sales = pd.read_csv("../data/car-sales.csv") # takes a filename as string as input

# Option 2: Read directly from a URL/Google Sheets
# If you are reading from GitHub, be sure to use the "raw" link (original link: https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/data/car-sales.csv)
car_sales = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales.csv")
car_sales

Now we've got the same data from the spreadsheet available in a pandas `DataFrame` called `car_sales`. 

Having your data available in a `DataFrame` allows you to take advantage of all of pandas functionality on it.

Another common practice you'll see is data being imported to `DataFrame` called `df` (short for `DataFrame`).

In [ ]:
# Import the car sales data and save it to df

# Option 1: Read from a CSV file (stored on our local computer)
df = pd.read_csv("../data/car-sales.csv")

# Option 2: Read directly from a URL/Google Sheets (if the file is hosted online)
df = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales.csv")
df

In [ ]:
# Export the car sales DataFrame to csv
car_sales.to_csv("../data/exported-car-sales.csv")

Running this will save a file called `export-car-sales.csv` to the current folder.

<img src="../images/pandas-exported-car-sales-csv.png" alt="folder with exported car sales csv file highlighted" width="600"/>

In [ ]:
# Your code here

In [ ]:
# Importing heart-disease.csv
patient_data = pd.read_csv("../data/heart-disease.csv")
patient_data

In [ ]:
# Exporting the patient_data DataFrame to csv
patient_data.to_csv("../data/exported-patient-data.csv")

<img src="../images/pandas-exported-patient-data-csv.png" alt="folder containing exported patient data csv file" width="600"/>

In [ ]:
car_sales

[`.dtypes`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dtypes.html) shows us what datatype each column contains.

In [ ]:
car_sales.dtypes

In [ ]:
car_sales.describe()

In [ ]:
car_sales.info()

In [ ]:
# Calling .mean() on a DataFrame
car_sales.mean(numeric_only=True) # numeric_only = get mean values of numeric columnns only

In [ ]:
# Calling .mean() on a Series
car_prices = pd.Series([3000, 3500, 11250])
car_prices.mean()

In [ ]:
# Calling .sum() on a DataFrame with numeric_only=False (default)
car_sales.sum(numeric_only=False)

In [ ]:
# Calling .sum() on a DataFrame with numeric_only=True
car_sales.sum(numeric_only=True)

In [ ]:
# Calling .sum() on a Series
car_prices.sum()

Calling these on a whole `DataFrame` may not be as helpful as targeting an individual column. But it's helpful to know they're there.

`.columns` will show you all the columns of a `DataFrame`.

In [ ]:
car_sales.columns

In [ ]:
# Save car_sales columns to a list 
car_columns = car_sales.columns
car_columns[0]

In [ ]:
car_sales.index

In [ ]:
# Show the length of a DataFrame
len(car_sales)

In [ ]:
# Show the first 5 rows of car_sales
car_sales.head()

In [ ]:
# Show the first 7 rows of car_sales
car_sales.head(7)

In [ ]:
# Show bottom 5 rows of car_sales
car_sales.tail()

In [ ]:
# Create a sample series
animals = pd.Series(["cat", "dog", "bird", "snake", "ox", "lion"], 
                    index=[0, 3, 9, 8, 67, 3])
animals

In [ ]:
# Select all indexes with 3
animals.loc[3]

In [ ]:
# Select index 9
animals.loc[9]

In [ ]:
car_sales

In [ ]:
# Select row at index 3
car_sales.loc[3]

[`iloc[]`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html) does a similar thing but works with exact positions.

In [ ]:
animals

In [ ]:
# Select row at position 3
animals.iloc[3]

Even though `'snake'` appears at index 8 in the series, it's shown using `.iloc[3]` because it's at the 3rd (starting from 0) position.

Let's try with the `car_sales` `DataFrame`.

In [ ]:
# Select row at position 3
car_sales.iloc[3]

You can see it's the same as `.loc[]` because the index is in order, position 3 is the same as index 3.

You can also use slicing with `.loc[]` and `.iloc[]`.

In [ ]:
# Get all rows up to position 3
animals.iloc[:3]

In [ ]:
# Get all rows up to (and including) index 3
car_sales.loc[:3]

In [ ]:
# Get all rows of the "Colour" column
car_sales.loc[:, "Colour"] # note: ":" stands for "all", e.g. "all indices in the first axis"

When should you use `.loc[]` or `.iloc[]`?
* Use `.loc[]` when you're selecting rows and columns **based on their lables or a condition** (e.g. retrieving data for specific columns).
* Use `.iloc[]` when you're selecting rows and columns **based on their integer index positions** (e.g. extracting the first ten rows regardless of the labels).

However, in saying this, it will often take a bit of practice with each of the methods before you figure out which you'd like to use.

If you want to select a particular column, you can use `DataFrame.['COLUMN_NAME']`.

In [ ]:
# Select Make column
car_sales['Make']

In [ ]:
# Select Colour column
car_sales['Colour']

Boolean indexing works with column selection too. Using it will select the rows which fulfill the condition in the brackets.

In [ ]:
# Select cars with over 100,000 on the Odometer
car_sales[car_sales["Odometer (KM)"] > 100000]

In [ ]:
# Select cars which are made by Toyota
car_sales[car_sales["Make"] == "Toyota"]

`pd.crosstab()` is a great way to view two different columns together and compare them.

In [ ]:
# Compare car Make with number of Doors
pd.crosstab(car_sales["Make"], car_sales["Doors"])

If you want to compare more columns in the context of another column, you can use `.groupby()`.

In [ ]:
car_sales

In [ ]:
# Group by the Make column and find the mean of the other columns 
car_sales.groupby(["Make"]).mean(numeric_only=True)

In [ ]:
# Import matplotlib and tell Jupyter to show plots
import matplotlib.pyplot as plt
%matplotlib inline

You can visualize a column by calling `.plot()` on it.

In [ ]:
car_sales["Odometer (KM)"].plot(); # tip: the ";" on the end prevents matplotlib from outputing the plot class

Or compare two columns by passing them as `x` and `y` to `plot()`.

In [ ]:
car_sales.plot(x="Make", y="Odometer (KM)");

You can see the distribution of a column by calling `.hist()` on you.

The distribution of something is a way of describing the spread of different values.

In [ ]:
car_sales["Odometer (KM)"].hist()

In this case, the majority of the **distribution** (spread) of the `"Odometer (KM)"` column is more towards the left of the graph. And there are two values which are more to the right. These two values to the right could be considered **outliers** (not part of the majority).

Now what if we wanted to plot our `"Price"` column?

Let's try.

In [ ]:
car_sales["Price"].plot()

Trying to run it leaves us with an error. This is because the `"Price"` column of `car_sales` isn't in numeric form. We can tell this because of the `TypeError: no numeric data to plot` at the bottom of the cell.

We can check this with `.info()`.

In [ ]:
car_sales.info()

In [ ]:
# Change Price column to integers
car_sales["Price"] = car_sales["Price"].str.replace('[\$\,\.]', '', regex=True)
car_sales

In [ ]:
# Remove 2 extra zeros from the price column (2200000 -> 22000) by indexing all but the last two digits
car_sales["Price"] = car_sales["Price"].str[:-2].astype(int)
car_sales

In [ ]:
car_sales.dtypes

Beautiful! Now let's try to plot it agian.

In [ ]:
car_sales["Price"].plot();

In [ ]:
# Lower the Make column
car_sales["Make"].str.lower()

In [ ]:
# View top 5 rows, Make column not lowered
car_sales.head()

In [ ]:
# Set Make column to be lowered
car_sales["Make"] = car_sales["Make"].str.lower()
car_sales.head()

In [ ]:
# Option 1: Import car sales data with missing values from local file (stored on our computer)
car_sales_missing = pd.read_csv("../data/car-sales-missing-data.csv")

# Option 2: Import car sales data with missing values from GitHub (if the file is hosted online)
car_sales_missing = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-missing-data.csv")
car_sales_missing

In [ ]:
# Fill Odometer column missing values with mean
car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(), 
                                     inplace=False) # inplace is set to False by default

Now let's check the original `car_sales_missing` `DataFrame`.

In [ ]:
car_sales_missing

In [ ]:
# Fill the Odometer missing values to the mean with inplace=True
car_sales_missing["Odometer"] = car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean())

Now let's check the `car_sales_missing` `DataFrame` again.

In [ ]:
car_sales_missing

In [ ]:
# Remove missing data
car_sales_missing.dropna()

It appears the rows with missing values have been removed, now let's check to make sure.

In [ ]:
car_sales_missing

In [ ]:
# The following two lines do the same thing
car_sales_missing.dropna(inplace=True) # Operation happens inplace without reassignment
car_sales_missing = car_sales_missing.dropna() # car_sales_missing gets reassigned to same DataFrame but with dropped values

Now if check again, the rows with missing values are gone and the index numbers have been updated.

In [ ]:
car_sales_missing

In [ ]:
# Create a column from a pandas Series
seats_column = pd.Series([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])
car_sales["Seats"] = seats_column
car_sales

In [ ]:
# Create a column from a Python list
engine_sizes = [1.3, 2.0, 3.0, 4.2, 1.6, 1, 2.0, 2.3, 2.0, 3.0]
car_sales["Engine Size"] = engine_sizes
car_sales

In [ ]:
# Column from other columns
car_sales["Price per KM"] = car_sales["Price"] / car_sales["Odometer (KM)"]
car_sales

Now can you think why this might not be a great column to add?

It could be confusing when a car with less kilometers on the odometer looks to cost more per kilometre than one with more. 

When buying a car, usually less kilometres on the odometer is better.

This kind of column creation is called [**feature engineering**](https://en.wikipedia.org/wiki/Feature_engineering), the practice of enriching your dataset with more information (either from it directly or elsewhere).

If `Make`, `Colour`, `Doors` are features of the data, creating `Price per KM` could be another. But in this case, not a very good one.

As for column creation, you can also create a new column setting all values to a one standard value.

In [ ]:
# Column to all 1 value (number of wheels)
car_sales["Number of wheels"] = 4
car_sales

In [ ]:
car_sales["Passed road safety"] = True
car_sales

Now you've created some columns, you decide to show your colleague what you've done. When they ask about the `Price per KM` column, you tell them you're not really sure why it's there.

You decide you better remove it to prevent confusion.

You can remove a column using [`.drop('COLUMN_NAME', axis=1)`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html).

In [ ]:
# Drop the Price per KM column
car_sales = car_sales.drop("Price per KM", axis=1) # columns live on axis 1
car_sales

In [ ]:
# Sample car_sales
car_sales_sampled = car_sales.sample(frac=1)
car_sales_sampled

In [ ]:
# Reset the indexes of car_sales_sampled
car_sales_sampled.reset_index()

In [ ]:
# Change the Odometer values from kilometres to miles
car_sales["Odometer (KM)"].apply(lambda x: x / 1.6)

Now let's check our `car_sales` `DataFrame`.

In [ ]:
car_sales

In [ ]:
# Reassign the Odometer column to be miles instead of kilometers
car_sales["Odometer (KM)"] = car_sales["Odometer (KM)"].apply(lambda x: x / 1.6)
car_sales

If you've never seen a lambda function they can be tricky. What the line above is saying is "take the value in the `Odometer (KM)` column (`x`) and set it to be itself divided by 1.6".